name: Run type check

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Test
        run: |
          npm install
          # Whack the deliberately broken file on the main branch. That way we
          # know this still works for the normal case.
          [[ $(git branch --show-current) == "main" ]] && rm index.ts
          npm test
